#######################################################################
#   Copyright [2014] [Cisco Systems, Inc.]
# 
#   Licensed under the Apache License, Version 2.0 (the \"License\");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an \"AS IS\" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#######################################################################

#
include $(CCSP_ROOT_DIR)/arch/ccsp_common.mk

#
#	Set up include directories
#
INCPATH += $(CCSP_OPENSOURCE_DIR)/include/curl-7.28.1

INCPATH += $(ComponentSrcDir)/Custom
INCPATH += $(ComponentSrcDir)/TR-181/include
INCPATH += $(ComponentSrcDir)/TR-181/middle_layer_src
INCPATH += $(ComponentArchSrcDir)/TR-181/arch_include
INCPATH += $(ComponentBoardSrcDir)/TR-181/board_include
INCPATH += $(CCSP_ROOT_DIR)/hal/include

# temporary fix -- 
INCPATH += $(ComponentBoardSrcDir)/TR-181/board_sbapi


CFLAGS += $(addprefix -I, $(INCPATH))

#
#	CM Ssp
#
source_files := $(call add_files_from_src,,'*.c')

target1 := $(ComponentBuildDir)/CcspCMAgentSsp
source_files1 := $(call add_files_from_src,CMAgentSsp,'*.c')
obj_files1 := $(addprefix $(ComponentBuildDir)/, $(source_files1:%.c=%.o))
-include $(obj_files1:.o=.d)

$(target1): $(obj_files1)

#
#	multiple targets are chained together
#
CMTargets := $(target1)


	# Make sure to replace TAB with spaces!!! Otherwise, the section below is considered part of the recipe above!
    target2 := $(ComponentBuildDir)/libcm_tr181.so
	CMTargets += $(target2)

	source_files2 += $(call add_files_from_src,TR-181/integration_src.shared,'*.c')
	source_files2 += $(call add_files_from_src,TR-181/middle_layer_src,'*.c')

	source_files2 += $(call add_files_from_arch,TR-181/arch_sbapi,'*.c')
	source_files2 += $(call add_files_from_arch,TR-181/arch_ml,'*.c')
	source_files2 += $(call add_files_from_board,TR-181/board_sbapi,'*.c')
	source_files2 += $(call add_files_from_board,TR-181/board_ml,'*.c')

	obj_files2 := $(addprefix $(ComponentBuildDir)/, $(source_files2:%.c=%.o))
	-include $(obj_files2:.o=.d)

$(target2): $(obj_files2)

#
#	Build targets
#
all: $(CMTargets)

.PHONY: all clean

clean:
	rm -Rf $(ComponentBuildDir)

install_targets := $(CMTargets)
install_targets += $(CCSP_OUT_DIR)/ccsp_msg.cfg
# config directories from both arch, arch-board, arch-board-customer
install_targets += $(wildcard $(ComponentArchCfgDir)/*)
install_targets += $(wildcard $(ComponentBoardCfgDir)/*)
install_targets += $(wildcard $(ComponentBoardCustomCfgDir)/*)
# scripts directories from arch, arch-board, arch-board-customer
install_targets += $(wildcard $(ComponentArchScriptsDir)/*)
install_targets += $(wildcard $(ComponentBoardScriptsDir)/*)
install_targets += $(wildcard $(ComponentBoardCustomScriptsDir)/*)


install:
	@echo "Installing CMAgent Installables"
	@install -d -m 0755 $(CCSP_OUT_DIR)/cm
	@cp -f $(install_targets) $(CCSP_OUT_DIR)/cm
    
LDFLAGS   += -lccsp_common

#
# include custom post makefile, if exists
#
ifneq ($(findstring $(CCSP_CMPNT_BUILD_CUSTOM_MK_POST), $(wildcard $(ComponentBoardDir)/*.mk)), )
    include $(ComponentBoardDir)/$(CCSP_CMPNT_BUILD_CUSTOM_MK_POST)
endif
